language: python
python:
- 3.6
- 3.7
- 3.8
- nightly
jobs:
  allow_failures:
  - python: nightly
addons:
  apt:
    packages:
    - python3-pip
services:
- docker
cache: pip
before_install:
- python3 -m pip install setuptools wheel
- python3 -m pip install git+https://github.com/jupyter/nbgrader.git
install:
- python3 -m pip install .
before_script:
- python3 -m pip install -r testing_reqs.txt
script:
- python3 -m black -S -l 80 --check .
- python3 -m pytest ./ngshare_exchange/ --cov=./ngshare_exchange/
after_success:
- codecov
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "Djx+Rp7LnP2HTU119oINJhJII4WBzhBHYcvYpwvHONkB+VJEGJB6N2r/aaen9WF+IQOlZ37ZyDhgsmi931gTbmdWAaL3+MAHkmkF5Psq/Mm4EBb3/ZU3iyDjMueaqjotMm6AmiA+RYnO6lsdaq/u26I8JcenLgHgS1VoAPsRRJ/hmUr5TmKi0B90z38nkhdr81W90JrjyQFHDTPO+J6lfHeDzhGnQCb4y8+iKySwGp6LUetssStdfb3XszQLKvhBRbCec3ZWdz3bru6JOLhlrDnDRqms3epURXlb5Vn7guBy9872Keng9wbku2Ng6tcKNhm/jWsYv5MC6McOcd2yW8u88DEzBo+pjf4Nsr4DBnFlld5fRSngnnJAOPPHEaIioPXk1ZbZRcVSN03Qn81wo1Tfyc6keq5brWPrFbHxpTUAhfX+hKwq/qITMBdZIXm+jOP4GQuvfYa4smLY0pLlCLGcMO/VL2gh4hJGtVtexP35yVF0s1UdUz6vkLfJ+OfXzJHf9DXYxjsHDy62y5w9VeET6mxDvwf7FGXGXDlVHcHcgYXC9IIGY7hLHqpG7lxhzHh7IumLYSTcWngriO11PKnt9tsyn9laqGdrmegnMe4RjbCiHxhO+8dfvuZifObuMgW0OF+P2MGHL/6ELxYJAY2mWIMHhpIFLS+v13ZwH+o="
  on:
    branch: stable
    python: "3.8"
